### ISSUE TITLE
Breaks things on Facter 3 environments

### ISSUE THREAD

**Issue by ananace** [optiz0r/puppet-sabayon#4]
With Puppet 4 and the packaged Facter 3.X version, there's a breaking bug in regards to overriding core facts. In this case, it means any non-Sabayon host in an environment where this module exists will receive the operatingsystem fact value of `null`.
This proves to be a Bad Thing™.

Upstream bug is [FACT-1528](https://tickets.puppetlabs.com/browse/FACT-1528).

What happens seems to be that Facter 3 and newer will always override a core fact with the same name, even when not resolving to anything at all, meaning the core fact will - in essence - disappear for all hosts where the custom fact doesn't resolve to anything.

**Comment by ananace** [comment]
Just to add an idea;

[Executable facts](https://docs.puppet.com/facter/3.6/custom_facts.html#executable-facts-----unix) exist - and have done so for a long time (Facter 1.7). Perhaps the best way to do something like this would be to add an executable fact that runs something like;

```sh
#!/bin/sh

. /etc/os-release
if [ "${ID}" == "sabayon" ]; then
  echo "operatingsystem=Sabayon"
fi
```

**Comment by optiz0r** [comment]
Thanks for raising this, I didn't encounter it because I'm only managing Sabayon hosts with my puppet setup. The best way to deal with this is get facter core to recognise Sabayon and remove the override entirely from this module (it was always a hack anyway).

Do you know what the precedence rules are where a facts.d replaces a core fact?

**Comment by ananace** [comment]
The precedence rules are something like this;

1. Environment variable (`FACTER_fact=value`)
2. Structured data fact (`facts.d/fact.yaml` / `facts.d/fact.json` / etc)
3. Executable data fact (`facts.d/fact.sh` / `facts.d/fact.py` / etc)
4. Custom fact (`lib/facter/fact.rb`)
5. Core fact
6. `null`

And I realized that the best way to do an executable fact would probably be;
```sh
#!/bin/sh

if [ -f /etc/sabayon-release ]; then
  echo "operatingsystem=Sabayon"
fi
```

Then it'll work even in environments where os-release isn't guaranteed to be sane on all hosts.

**Comment by optiz0r** [comment]
That makes sense. I suggest implementing this is probably a good quick fix, and getting Facter to support Sabayon properly is the best long-term fix. It's getting late for me tonight, so I can look at implementing this tomorrow evening, or if you want to get there first PRs welcome.

**Comment by optiz0r** [comment]
I had to mark the fact as executable to make it work, but done, bumped to 0.4.0, and pushed to the forge.
Thanks!
